---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by snake.
--- DateTime: 2019/12/8 23:51
---


local V = {}
function V:start()
    print("登录界面")
    print(self.nameNode)

    local nameFiled =  GetObjComponent(self.nameNode,UI.InputField)
    local passwdFiled =  GetObjComponent(self.passwdNode,UI.InputField)
    
    
    print(nameFiled.text)

    RPCInstance:Connect("127.0.0.1:50051");
    local request = CS.NetLib.CommonUser.UserReply()
    
    print(type(request))
    local reply =  RPCInstance:Protocol_CreateUser( request);
    print(reply)
end


return V